import { League_Spartan } from "next/font/google";
import "./globals.css";

const leagueSpartan = League_Spartan({
  variable: "--font-league-spartan",
  weight: ["500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Room Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/favicon/icon.png"
          type="image/png"
          sizes="32x32"
        />
      </head>
      <body
        className={`${leagueSpartan.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
